version: '3.7'

services:
  bss-tests:
    hostname: bss-tests
    container_name: bss-tests
    image: ghcr.io/openchami/hurl-test
    volumes:
      - ./tests/smd-auth-bss-noauth:/tests:ro
    networks:
      - internal
    depends_on:
        smd:
          condition: service_healthy
        bss:
          condition: service_healthy
